module.exports = overlays = [
  // Commands
  {
    name: 'hpcwins',
    type: 'video',
    file: 'overlays/events/hpcwins.mp4'
  }, {
    name: 'powermove',
    type: 'video',
    file: 'overlays/events/powermove.mp4'
  }, {
    name: 'tworax',
    type: 'video',
    file: 'overlays/events/tworax.mp4'
  }, {
    name: 'gift',
    type: 'video',
    file: 'overlays/events/gift.mp4'
  }, {
    name: 'cheese',
    type: 'video',
    file: 'overlays/events/cheese.mp4'
  }, {
    name: 'smoke',
    type: 'video',
    file: 'overlays/events/smokegank.mp4'
  }, {
    name: 'muggle',
    type: 'video',
    file: 'overlays/events/muggle.mp4'
  }, {
    name: 'sacrifice',
    type: 'video',
    file: 'overlays/events/sacrifice.mp4'
  }, {
    // First Blood
    name: 'first',
    type: 'video',
    file: 'overlays/events/Firstblood.mp4'
  }, {
    name: 'buyback',
    type: 'video',
    file: 'overlays/events/Buyback.mp4'
  }, {
    name: 'open',
    type: 'video',
    file: 'overlays/events/Opening.mp4'
  }, {
    name: 'close',
    type: 'video',
    file: 'overlays/events/Closing.mp4'
  }, {
    // Fake Ads
    name: 'kia',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/kia.mp4'
  }, {
    name: 'monster',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/monster.mp4'
  }, {
    name: 'polo',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/Polo.mp4'
  }, {
    name: 'hweengwin',
    type: 'video',
    file: 'overlays/events/HweenGWin.mp4'
  }, {
    name: 'hweenglose',
    type: 'video',
    file: 'overlays/events/HweenGLose.mp4'
  }, {
    name: 'hweenhwin',
    type: 'video',
    file: 'overlays/events/HweenHWin.mp4'
  }, {
    name: 'hweenhlose',
    type: 'video',
    file: 'overlays/events/HweenHLose.mp4'
  }, {
    name: 'hweenrwin',
    type: 'video',
    file: 'overlays/events/HweenRWin.mp4'
  }, {
    name: 'hweenrlose',
    type: 'video',
    file: 'overlays/events/HweenRLose.mp4'
  }, {
    name: 'hweenswin',
    type: 'video',
    file: 'overlays/events/HweenSWin.mp4'
  }, {
    name: 'hweenslose',
    type: 'video',
    file: 'overlays/events/HweenSLose.mp4'
  }, {
    name: 'ag5',
    type: 'video',
    file: 'overlays/events/05PointsGryffindor.mp4'
  }, {
    name: 'ag10',
    type: 'video',
    file: 'overlays/events/10PointsGryffindor.mp4'
  }, {
    name: 'ah5',
    type: 'video',
    file: 'overlays/events/05PointsHufflepuff.mp4'
  }, {
    name: 'ah10',
    type: 'video',
    file: 'overlays/events/10PointsHufflepuff.mp4'
  }, {
    name: 'ar5',
    type: 'video',
    file: 'overlays/events/05PointsRavenclaw.mp4'
  }, {
    name: 'ar10',
    type: 'video',
    file: 'overlays/events/10PointsRavenclaw.mp4'
  }, {
    name: 'as5',
    type: 'video',
    file: 'overlays/events/05PointsSlytherin.mp4'
  }, {
    name: 'as10',
    type: 'video',
    file: 'overlays/events/10PointsSlytherin.mp4'
  }, {
    name: 'minuspoints',
    type: 'video',
    file: 'overlays/events/MinusPoints.mp4'
  }, {
    name: 'cuphwins',
    type: 'video',
    file: 'overlays/events/HufflepuffWins.mp4'
  }, {
    name: 'cupgwins',
    type: 'video',
    file: 'overlays/events/GryffindorWins.mp4'
  }, {
    name: 'cuprwins',
    type: 'video',
    file: 'overlays/events/RavenclawWins.mp4'
  }, {
    name: 'cupswins',
    type: 'video',
    file: 'overlays/events/SlytherinWins.mp4'
  }, {
    // Goblin Gold
    name: 'gold',
    type: 'video',
    file: 'overlays/events/gold.mp4'
  }, {
    // Quidditch
    name: 'qgw',
    type: 'video',
    file: 'overlays/events/QuidditchGryffindorWin.mp4'
  }, {
    name: 'qrw',
    type: 'video',
    file: 'overlays/events/QuidditchRavenclawWin.mp4'
  }, {
    name: 'qhw',
    type: 'video',
    file: 'overlays/events/QuidditchHufflepuffWin.mp4'
  }, {
    name: 'qsw',
    type: 'video',
    file: 'overlays/events/QuidditchSlytherinWin.mp4'
  },{
    name: '3runes',
    type: 'video',
    file: 'overlays/events/runes.mp4'
  }, {
    name: 'text',
    type: 'text'
  }];
