module.exports = overlays = [
  // Commands
  {
    name: 'hpcwins',
    type: 'video',
    file: 'overlays/events/hpcwins2018.mp4'
  }, {
    name: 'powermove',
    type: 'video',
    file: 'overlays/events/powermove.mp4'
  }, {
    name: 'tworax',
    type: 'video',
    file: 'overlays/events/tworax.mp4'
  }, {
    name: 'gift',
    type: 'video',
    file: 'overlays/events/gift.mp4'
  }, {
    name: 'cheese',
    type: 'video',
    file: 'overlays/events/cheese.mp4'
  }, {
    name: 'smoke',
    type: 'video',
    file: 'overlays/events/smokegank.mp4'
  }, {
    name: 'muggle',
    type: 'video',
    file: 'overlays/events/muggle.mp4'
  }, {
    name: 'sacrifice',
    type: 'video',
    file: 'overlays/events/sacrifice.mp4'
  }, {
    // First Blood
    name: 'first',
    type: 'video',
    file: 'overlays/events/Firstblood.mp4'
  }, {
    name: 'buyback',
    type: 'video',
    file: 'overlays/events/Buyback.mp4'
  }, {
    name: 'opening',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/Opening.mp4'
  }, {
    name: 'closing',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/Closing.mp4'
  }, {
    // Fake Ads
    name: 'goodhumour',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/goodhumour.webm'
  }, {
    name: 'kia',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/kia.webm'
  }, {
    name: 'monster',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/monster.webm'
  }, {
    name: 'polo',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/Polo.webm'
  }, {
    name: 'dumbledoors',
    type: 'video',
    file: 'overlays/ads/dumbledoors.mp4'
  }, {
    name: 'segway',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/segway.webm'
  },{
    name: 'culvers',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/ads/culvers.webm'
  },

  {
    name: 'hweengwin',
    type: 'video',
    file: 'overlays/events/HweenGWin.mp4'
  }, {
    name: 'hweenglose',
    type: 'video',
    file: 'overlays/events/HweenGLose.mp4'
  }, {
    name: 'hweenhwin',
    type: 'video',
    file: 'overlays/events/HweenHWin.mp4'
  }, {
    name: 'hweenhlose',
    type: 'video',
    file: 'overlays/events/HweenHLose.mp4'
  }, {
    name: 'hweenrwin',
    type: 'video',
    file: 'overlays/events/HweenRWin.mp4'
  }, {
    name: 'hweenrlose',
    type: 'video',
    file: 'overlays/events/HweenRLose.mp4'
  }, {
    name: 'hweenswin',
    type: 'video',
    file: 'overlays/events/HweenSWin.mp4'
  }, {
    name: 'hweenslose',
    type: 'video',
    file: 'overlays/events/HweenSLose.mp4'
  }, {
    name: 'ag5',
    type: 'video',
    file: 'overlays/events/05PointsGryffindor.mp4'
  }, {
    name: 'ag10',
    type: 'video',
    file: 'overlays/events/10PointsGryffindor.mp4'
  }, {
    name: 'ah5',
    type: 'video',
    file: 'overlays/events/05PointsHufflepuff.mp4'
  }, {
    name: 'ah10',
    type: 'video',
    file: 'overlays/events/10PointsHufflepuff.mp4'
  }, {
    name: 'ar5',
    type: 'video',
    file: 'overlays/events/05PointsRavenclaw.mp4'
  }, {
    name: 'ar10',
    type: 'video',
    file: 'overlays/events/10PointsRavenclaw.mp4'
  }, {
    name: 'as5',
    type: 'video',
    file: 'overlays/events/05PointsSlytherin.mp4'
  }, {
    name: 'as10',
    type: 'video',
    file: 'overlays/events/10PointsSlytherin.mp4'
  }, {
    name: 'minuspoints',
    type: 'video',
    file: 'overlays/events/MinusPoints.mp4'
  }, {
    name: 'cuphwins',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/HufflepuffWins.webm'
  }, {
    name: 'cupgwins',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/GryffindorWins.webm'
  }, {
    name: 'cuprwins',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/RavenclawWins.webm'
  }, {
    name: 'cupswins',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/SlytherinWins.webm'
  }, {
    // Goblin Gold
    name: 'gold',
    type: 'video',
    file: 'overlays/events/gold.mp4'
  }, {
    // Quidditch
    name: 'qgw',
    type: 'video',
    file: 'overlays/events/QuidditchGryffindorWin.mp4'
  }, {
    name: 'qrw',
    type: 'video',
    file: 'overlays/events/QuidditchRavenclawWin.mp4'
  }, {
    name: 'qhw',
    type: 'video',
    file: 'overlays/events/QuidditchHufflepuffWin.mp4'
  }, {
    name: 'qsw',
    type: 'video',
    file: 'overlays/events/QuidditchSlytherinWin.mp4'
  },{
    name: '3runes',
    type: 'video',
    file: 'overlays/events/runes.mp4'
  },{
    name: 'picks',
    type: 'video',
    file: 'overlays/events/QualityPicks.mp4'
  },{
    name: '4runes',
    type: 'video',
    file: 'overlays/events/4runes.mp4'
  },{
    name: 'juked',
    type: 'video',
    file: 'overlays/events/juked.mp4'
  },{
    name: 'suicidepact',
    type: 'video',
    file: 'overlays/events/suicidepact.mp4'
  },{
    name: 'teamwork',
    type: 'video',
    file: 'overlays/events/teamwork.mp4'
  },{
    name: 'justscummy',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/justscummy.webm'
  },{
    name: 'fullpurge',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/fullpurge.webm'
  },{
    name: 'fallingrunes',
    type: 'video',
    layout: 'fullscreen',
    file: 'overlays/events/fallingrunes.webm'
  },{
    name: 'text',
    type: 'text'
  }];
